#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue May 05 10:58:11 PDT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=14
shaderPack=PotatoShaders_v1.0d.zip
enableShaders=false
